version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8-jdk-alpine
    steps:
      - checkout
      - run: mvn clean package
  test:
    docker:
      - image: circleci/java:8-jdk-alpine
    steps:
      - checkout
      - run: mvn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test