version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Create Package
          command: echo "master"
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Test
          command:  echo "test finished"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test